# Generated by Django 5.0.6 on 2024-06-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0002_doctor_event_microchip_owner_shelter_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='eye_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='last_known_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dog',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
