# Generated by Django 5.0.6 on 2024-06-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0002_command_doctor_event_microchip_owner_shelter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
