# Generated by Django 5.0.6 on 2024-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0003_dog_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_phone', models.CharField(max_length=15)),
                ('facebook_profile', models.URLField(blank=True, null=True)),
                ('instagram_profile', models.URLField(blank=True, null=True)),
                ('adults_in_home', models.PositiveIntegerField()),
                ('children_info', models.TextField()),
                ('allergies', models.BooleanField()),
                ('home_type', models.CharField(choices=[('House', 'Μονοκατοικία'), ('Apartment', 'Πολυκατοικία'), ('Other', 'Άλλο')], max_length=50)),
                ('fence_height', models.FloatField()),
                ('escape_possibility', models.BooleanField()),
                ('current_pets', models.TextField(blank=True, null=True)),
                ('past_pets', models.TextField(blank=True, null=True)),
                ('abandoned_pet', models.BooleanField()),
                ('adopted_before', models.BooleanField()),
                ('adoption_reason', models.CharField(max_length=255)),
                ('family_agreement', models.BooleanField()),
                ('caretaker_info', models.TextField()),
                ('plan_to_neuter', models.BooleanField()),
                ('if_not_neuter_reason', models.TextField(blank=True, null=True)),
                ('pet_location_day_home', models.CharField(max_length=255)),
                ('pet_location_day_away', models.CharField(max_length=255)),
                ('pet_location_night', models.CharField(max_length=255)),
                ('pet_location_long_absence', models.CharField(max_length=255)),
                ('walk_time', models.CharField(max_length=255)),
                ('alone_time', models.PositiveIntegerField()),
                ('moving_plan', models.TextField()),
                ('bad_behavior_response', models.TextField()),
                ('preferences', models.TextField(blank=True, null=True)),
                ('pet_character', models.TextField()),
                ('willing_to_host_special_needs', models.TextField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('accepted_terms', models.BooleanField()),
            ],
        ),
    ]
