# Generated by Django 5.0.6 on 2024-06-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0003_dog_color_dog_eye_color_dog_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogBreedPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('predicted_breed', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('related_dog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Paws.dog')),
            ],
        ),
    ]
