# Generated by Django 5.0.6 on 2024-06-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0005_remove_userprofile_role_userprofile_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groomer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='groomer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='groomer',
            name='phone',
        ),
    ]
