# Generated by Django 5.0.6 on 2024-06-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0006_userprofile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='dental_health',
            field=models.BooleanField(default=False, help_text='Is this food beneficial for dental health?'),
        ),
        migrations.AddField(
            model_name='food',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='Any dietary restrictions this food addresses'),
        ),
        migrations.AddField(
            model_name='food',
            name='digestion_health',
            field=models.BooleanField(default=False, help_text='Is this food beneficial for digestion health?'),
        ),
        migrations.AddField(
            model_name='food',
            name='nutritional_content',
            field=models.TextField(default='Not specified', help_text='Detailed nutritional content of the food'),
        ),
        migrations.AddField(
            model_name='food',
            name='skin_and_coat_health',
            field=models.BooleanField(default=False, help_text='Is this food beneficial for skin and coat health?'),
        ),
        migrations.AddField(
            model_name='food',
            name='suitable_for_age_groups',
            field=models.CharField(default='All', help_text='Age groups like puppy, adult, senior', max_length=100),
        ),
        migrations.AddField(
            model_name='food',
            name='weight_management',
            field=models.BooleanField(default=False, help_text='Is this food suitable for weight management?'),
        ),
    ]
