# Generated by Django 5.0.6 on 2024-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0007_food_dental_health_food_dietary_restrictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='health',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='dental_health',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='digestive_health',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='health',
            name='hearing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='heart_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='musculoskeletal_health',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='health',
            name='respiratory_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='skin_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='health',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='vision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='health',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='health',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
