# Generated by Django 5.0.6 on 2024-06-09 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0008_breed_coat_length_breed_exercise_needs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='groomer',
            name='groomer',
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='userprofile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='Paws.userprofile'),
        ),
        migrations.AddField(
            model_name='groomer',
            name='grooming_experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groomer',
            name='userprofile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='groomer_profile', to='Paws.userprofile'),
        ),
        migrations.AddField(
            model_name='owner',
            name='userprofile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='Paws.userprofile'),
        ),
        migrations.AddField(
            model_name='shelter',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='userprofile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='shelter_profile', to='Paws.userprofile'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='shedding',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('none', 'None')], default='low', max_length=20),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='doctor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_profile', to='Paws.doctor'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='groomer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groomer_profile', to='Paws.groomer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_profile', to='Paws.owner'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shelter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shelter_profile', to='Paws.shelter'),
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.IntegerField(blank=True, null=True)),
                ('userprofile', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sitter_profile', to='Paws.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sitter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sitter_profile', to='Paws.sitter'),
        ),
        migrations.CreateModel(
            name='Walker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walking_experience_years', models.IntegerField(blank=True, null=True)),
                ('userprofile', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='walker_profile', to='Paws.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='walker',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walker_profile', to='Paws.walker'),
        ),
    ]
