# Generated by Django 5.0.6 on 2024-06-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0009_dogbreedprediction_comments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredictionRating',
        ),
    ]
