# Generated by Django 5.0.6 on 2024-06-09 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0009_remove_doctor_specialty_remove_groomer_groomer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='Paws.userprofile'),
        ),
        migrations.AlterField(
            model_name='groomer',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groomer_profile', to='Paws.userprofile'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to='Paws.userprofile'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shelter_profile', to='Paws.userprofile'),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sitter_profile', to='Paws.userprofile'),
        ),
        migrations.AlterField(
            model_name='walker',
            name='userprofile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='walker_profile', to='Paws.userprofile'),
        ),
    ]
