# Generated by Django 5.0.6 on 2024-06-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0010_alter_doctor_userprofile_alter_groomer_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='image',
            field=models.ImageField(blank=True, default='breed_images/default.jpg', null=True, upload_to='breed_images/'),
        ),
    ]
