# Generated by Django 5.0.6 on 2024-06-04 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Paws", "0010_delete_predictionrating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="health",
            name="is_sick",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="walk",
            name="sitter_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="walk",
            name="walker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
