# Generated by Django 5.0.6 on 2024-06-06 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Paws", "0011_health_is_sick_walk_sitter_required_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Command",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="email",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="owner",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="owner",
            name="number_of_dogs",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="training",
            name="trainer_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="first_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_name",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="training",
            name="commands",
            field=models.ManyToManyField(blank=True, to="Paws.command"),
        ),
        migrations.CreateModel(
            name="Groomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=255)),
                (
                    "groomer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Grooming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("notes", models.TextField()),
                (
                    "dog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Paws.dog"
                    ),
                ),
                (
                    "groomer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Paws.groomer"
                    ),
                ),
            ],
        ),
    ]
