# Generated by Django 5.0.6 on 2024-06-09 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0013_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_trainer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.IntegerField()),
                ('specialties', models.TextField(blank=True, null=True)),
                ('userprofile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to='Paws.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_profile', to='Paws.trainer'),
        ),
    ]
