# Generated by Django 5.0.6 on 2024-06-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0015_dog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='adoption_status',
            new_name='is_not_adopted',
        ),
    ]
