# Generated by Django 5.0.6 on 2024-06-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0019_alter_shelter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='experience_years',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
