# Generated by Django 5.0.6 on 2024-06-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paws', '0021_remove_shelter_email_remove_shelter_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='postal_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
